spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_web_data
    username: mosh
    password: mode0520
    #    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 1000

# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8000
#  configuration:
#    map-underscore-to-camel-case: true

#  与欢迎页和favicon冲突
#  mvc:
#    static-path-pattern: /res/**

